embed_ptx(
  OUTPUT_TARGET
  spherePathTracer_devicePrograms
  PTX_LINK_LIBRARIES
  gdt
  SOURCES
  devicePrograms.cu
)

add_executable(spherePathTracer_SBTData
  optix7.h
  CUDABuffer.h
  LaunchParams.h
  SphereRenderer.h
  SphereRenderer.cpp
  main.cpp
  ../include/3rdParty/imgui/imgui.cpp
  ../include/3rdParty/imgui/imgui_demo.cpp
  ../include/3rdParty/imgui/imgui_draw.cpp
  ../include/3rdParty/imgui/imgui_tables.cpp
  ../include/3rdParty/imgui/imgui_widgets.cpp
  ../include/3rdParty/imgui/backends/imgui_impl_glfw.cpp
  ../include/3rdParty/imgui/backends/imgui_impl_opengl3.cpp
  )

target_link_libraries(spherePathTracer_SBTData
  spherePathTracer_devicePrograms
  gdt
  glfWindow
  )
